package com.example.demo;

public class QuestionGenerator {
  private String[] allQs = {
    "The time complexity of an algorithm is the amount of memory required to run the algorithm.",
    "A stack is a Last-In-First-Out (LIFO) data structure.",
    "In a binary search tree, the left child of a node is always smaller than the node's value.",
    "The space complexity of an algorithm describes how much time the algorithm will take to run.",
    "A quicksort algorithm has an average time complexity of O(n log n).",
    "In an algorithm, the Big O notation describes the worst-case time complexity.",
    "A hash table is a data structure that uses key-value pairs to store data.",
    "A depth-first search (DFS) algorithm uses a queue to keep track of nodes to explore.",
    "A binary search requires a sorted array to work properly.",
    "A linked list is an example of a random access data structure.",
    "The quicksort algorithm is always faster than merge sort.",
    "In a directed graph, edges have a direction associated with them.",
    "In an undirected graph, there is no difference between the edges going from node A to node B and vice versa.",
    "A heap data structure is typically implemented as a binary tree.",
    "An AVL tree is a self-balancing binary search tree.",
    "The breadth-first search (BFS) algorithm always finds the shortest path in an unweighted graph.",
    "A queue is a Last-In-First-Out (LIFO) data structure.",
    "The Dijkstra algorithm is used for finding the shortest path in a weighted graph.",
    "The Merge Sort algorithm is a comparison-based sorting algorithm.",
    "The time complexity of insertion sort in the worst case is O(n log n).",
    "A Turing machine can simulate any algorithm that can be executed by a modern computer.",
    "In a binary search tree, the inorder traversal of the tree produces a sorted sequence of values.",
    "A regular expression can be used to search for patterns in text.",
    "An algorithm with time complexity O(n^2) will run slower than one with time complexity O(n log n) for large input sizes.",
    "Dynamic programming is a technique used to solve problems by breaking them down into simpler subproblems.",
    "A class in object-oriented programming is a template for creating objects.",
    "In object-oriented programming, inheritance allows a subclass to access the methods and attributes of its superclass.",
    "Encapsulation refers to the hiding of an object’s state and requiring all interaction to be performed through methods.",
    "Polymorphism in object-oriented programming allows objects of different classes to be treated as objects of a common superclass.",
    "Recursion is a technique in programming where a function calls itself to solve a problem.",
    "A binary search tree can store duplicate values.",
    "An interface in Java can contain implementation details of its methods.",
    "All algorithms that solve NP-complete problems can be solved in polynomial time.",
    "Big O notation is used to describe the efficiency of an algorithm in terms of time or space.",
    "A graph can only have directed edges.",
    "A queue follows the FIFO (First-In-First-Out) principle.",
    "Merge sort is an example of a divide-and-conquer algorithm.",
    "A breadth-first search (BFS) is implemented using a stack.",
    "Binary search can be used on unsorted data.",
    "An algorithm with a time complexity of O(1) is considered constant time.",
    "The Fibonacci sequence can be computed using dynamic programming.",
    "The RSA algorithm is based on the principle of factoring large prime numbers.",
    "A Turing machine is capable of solving every problem that is computable.",
    "A Trie is a tree-like data structure used for efficient searching of strings.",
    "A directed acyclic graph (DAG) contains no cycles.",
    "A bubble sort algorithm has a time complexity of O(n^2) in the worst case.",
    "An undersized hash table can cause excessive collisions and degrade performance.",
    "A linked list can be traversed in both directions if it is doubly linked.",
    "The Bellman-Ford algorithm can handle negative edge weights in a graph.",
    "The greedy algorithm always produces the optimal solution to every problem.",
    "JavaScript is a statically typed programming language.",
    "A kernel is the core part of an operating system that manages hardware and software resources.",
    "Deadlock can occur when two or more processes are blocked forever waiting for resources.",
    "A virtual machine is a software-based simulation of physical hardware.",
    "An operating system’s scheduler decides which processes should be executed next.",
    "An open-source software license allows anyone to view and modify the source code.",
    "Encryption is the process of converting data into a form that is unreadable without the appropriate key.",
    "A client-server architecture relies on clients requesting services from a central server.",
    "An IPv4 address consists of 128 bits.",
    "DNS (Domain Name System) is used to resolve human-readable domain names into IP addresses.",
    "A subnet mask is used to divide an IP address into network and host portions.",
    "The IPv6 protocol was developed to replace IPv4 due to the limited number of available IP addresses in IPv4.",
    "Cloud computing refers to the delivery of computing resources as services over the internet.",
    "An API (Application Programming Interface) allows different software applications to communicate with each other.",
    "SQL is used to define and manipulate relational databases.",
    "A deadlock can be avoided by ensuring that no circular waits occur in a system.",
    "Concurrency refers to multiple tasks being executed simultaneously.",
    "Machine learning is a subset of artificial intelligence focused on making predictions based on data.",
    "A neural network is a type of machine learning algorithm inspired by the structure of the human brain.",
    "Supervised learning requires labeled data for training a model.",
    "Overfitting occurs when a machine learning model is too complex and fits the training data too closely.",
    "A decision tree is a supervised learning algorithm used for both classification and regression tasks.",
    "Genetic algorithms are inspired by the process of natural selection.",
    "An operating system manages process scheduling, memory allocation, and device management.",
    "System calls allow programs to interact with the operating system.",
    "Cache memory is used to store frequently accessed data to speed up computing processes.",
    "An operating system kernel operates in user mode, providing an interface to programs.",
    "A context switch refers to the process of saving and restoring the state of a CPU between different processes.",
    "Deep learning models require large amounts of labeled data for training.",
    "Cloud storage refers to storing data in physical hardware that is located in a private server."
  };
  private String[] allAs = {
    "False",
    "True" ,
    "True" ,
    "False",
    "True" ,
    "True" ,
    "True" ,
    "False",
    "True" ,
    "False",
    "False",
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "False",
    "True" ,
    "True" ,
    "True" ,
    "False",
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "False",
    "True" ,
    "True" ,
    "True" ,
    "False",
    "True" ,
    "True" ,
    "False",
    "True" ,
    "True" ,
    "False",
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" ,
    "True" 
  };

  public int seedIndex() {
    return (int)(Math.random() * this.allQs.length);
  }

  public int incIndex(int idx) {
    return (idx + 1) % this.allQs.length;
  }

  public String getQuestion(int idx) {
      return this.allQs[idx];
  }

  public String getAnswer(int idx) {
      return this.allAs[idx];
  }
}